### PR TITLE
List of vertex generators in MCC2

### PR DESCRIPTION
**Pull request by cherylepatrick**

### CODE REVIEW

**Comment by cherylepatrick** [comment]
List of vertex generators used in MCC2, with pictures. A few questions:

- Is there a reason we don't have a vertex generator for the X-wall and veto PMT glass? Am I wrong that we don't have it?
- What's the status of the calibration source modelling? In the version of flsimulate-configure that I have, the vertex generator is greyed out and I can't generate with that vertex.
- MCC2 has calorimeter wrappers included on the to-do list, but only for the main wall. I guess that's the most likely to cause problems, but in the long term, should we simulate for X wall and veto as well?

Can someone take a look at this and tell me whether they agree that this is a decent and correct list? @emchauve ? @lemiere ?

**Comment by cherylepatrick** [comment]
Edit to add - this is for issue #2

**Comment by lemiere** [comment]
Hi Cheryl,

1)  vertex generator for the X-wall and veto PMT glass do not exist for now. 
2) Firstable Demonstrator geometry (first tab) active the source calibration deployement. So the vertex generator 'source calibration all spot' is available
3) I'm a bit confused... Normally the calo_wrapper vertex generator is done for the full set of OM. I will check tomorrow and let you know.

**Comment by cherylepatrick** [comment]
Thank you @lemiere ! I'll see if I can make the calibration one and add an example to the document. I might have done something wrong for the calo_wrapper - thanks for looking at it for me. Just let me know if there's something I'm missing and I can re-do it.

**Comment by cherylepatrick** [comment]
Calibration sources added! I'll wait and see if Yves can figure out what I did wrong with the calo_wrapper and then consider this section done.

**Pull request merged**
